from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run():
    app_js = (ROOT / "app" / "app.js").read_text(encoding="utf-8")
    styles = (ROOT / "app" / "styles.css").read_text(encoding="utf-8")
    html = (ROOT / "app" / "index.html").read_text(encoding="utf-8")

    assert 'id="timeline"' in html
    assert "timeline-playhead" in app_js
    assert "updatePlaybackProgress" in app_js
    assert '$("timeline").addEventListener("click"' in app_js
    assert ".timeline-playhead" in styles
    assert "video.currentTime - viewport.start" in app_js
    assert "viewport.end - viewport.start" in app_js
    assert "analysisProgressBar" in app_js
    assert "formatRemaining" in app_js
    assert "uploadAnalysisJob" in app_js
    assert "waitForAnalysisResult" in app_js
    assert "cancelAnalysis" in app_js
    assert 'id="analysisEta"' in html
    assert 'id="cancelAnalyzeBtn"' in html
    assert 'id="addHitBtn"' in html
    assert "addHitAtCurrentTime" in app_js
    assert "reviewStatus" in app_js
    assert "renderCuts" in app_js
    assert "rebuildHighlights" in app_js
    assert 'id="trainingReport"' in html
    assert "buildTrainingSummary" in app_js
    assert "downloadTrainingReport" in app_js
    assert "getHighlightScore" in app_js
    assert "getExportSegments" in app_js
    assert "favorite" in app_js
    assert 'id="reuseCache"' in html
    assert "indexedDB.open" in app_js
    assert "readAnalysisCache" in app_js
    assert "writeAnalysisCache" in app_js
    assert 'id="calibrateBallBtn"' in html
    assert "sampleBallColor" in app_js
    assert "ballColor" in app_js
    assert "cameraStability" in app_js
    assert "recommendations" in app_js
    assert "projectStoreName" in app_js
    assert "writeProjectEdits" in app_js
    assert "applyProjectEdits" in app_js
    assert 'id="previousEventBtn"' in html
    assert 'id="nextEventBtn"' in html
    assert "navigateEvent" in app_js
    assert "handleEditorShortcut" in app_js
    assert 'id="hitSensitivity"' in html
    assert "sensitivity" in app_js
    assert "text/html;charset=utf-8" in app_js
    assert "剪球训练报告" in app_js
    assert 'id="bestHighlightBtn"' in html
    assert 'id="downloadCoverBtn"' in html
    assert "downloadCover" in app_js
    assert "getBestHighlight" in app_js
    assert 'id="keepAudio"' in html
    assert "getAudioTracks" in app_js
    assert "activeJobStorageKey" in app_js
    assert "resumeActiveAnalysis" in app_js
    assert "X-Jianqiu-Cache-Key" in app_js
    assert 'id="autoSlowMotion"' in html
    assert "updatePreviewPlaybackRate" in app_js
    assert 'id="copyCaptionBtn"' in html
    assert "buildSocialCaption" in app_js
    assert "copySocialCaption" in app_js
    assert 'id="eventFilter"' in html
    assert 'id="confirmHighBtn"' in html
    assert "confirmHighConfidenceEvents" in app_js
    assert 'id="undoEditBtn"' in html
    assert 'id="redoEditBtn"' in html
    assert "undoEdit" in app_js
    assert "redoEdit" in app_js
    assert 'id="effectStyle"' in html
    assert 'id="showTrajectory"' in html
    assert 'id="showImpact"' in html
    assert "getEffectSettings" in app_js
    assert 'id="importProjectBtn"' in html
    assert 'id="projectInput"' in html
    assert "importProjectFile" in app_js
    assert 'id="shotMap"' in html
    assert "renderShotMap" in app_js
    assert "locateShotMapEvent" in app_js
    assert 'id="analysisPreset"' in html
    assert "analysisPreset" in app_js
    assert 'id="markCutStartBtn"' in html
    assert 'id="finishCutBtn"' in html
    assert "finishManualCut" in app_js
    assert "rebuildSegmentsFromCuts" in app_js
    assert "shotType" in app_js
    assert "getShotTypeLabel" in app_js
    assert "教练备注" in app_js
    assert "checkLocalAnalyzerEnvironment" in app_js
    assert "/api/system" in app_js
    assert 'id="downloadCsvBtn"' in html
    assert "downloadTrainingCsv" in app_js
    assert 'id="trainingHistoryList"' in html
    assert "historyStoreName" in app_js
    assert "writeTrainingHistory" in app_js
    assert "renderTrainingHistory" in app_js
    assert 'id="historyChart"' in html
    assert "drawHistoryChart" in app_js
    assert 'id="historyBaselineSelect"' in html
    assert 'id="trainingComparison"' in html
    assert "renderTrainingComparison" in app_js
    assert "每分钟有效击球" in app_js
    assert ".training-comparison" in styles
    assert 'id="rallyList"' in html
    assert "buildRallies" in app_js
    assert "renderRallies" in app_js
    assert 'id="clearLocalDataBtn"' in html
    assert "clearLocalAnalysisData" in app_js
    assert "indexedDB.deleteDatabase" in app_js
    assert "segment.camera" in styles
    assert 'class="camera"' in html
    assert "getEstimatedAnalysisSeconds" in app_js
    assert "updateProcessingBenchmark" in app_js
    assert "localStorage.setItem" in app_js
    assert "validEvent" in app_js
    assert "validSegment" in app_js
    assert "validPoint" in app_js
    assert "positionEventId" in app_js
    assert "handlePlayerFrameClick" in app_js
    assert 'data-action="relocate"' in app_js
    assert 'id="highlightThreshold"' in html
    assert "getHighlightThreshold" in app_js
    assert "getSelectedHighlights" in app_js
    assert "正在导出片段" in app_js
    assert "completedSourceSeconds" in app_js
    assert 'id="smartReframe"' in html
    assert "getTrackingFocus" in app_js
    assert "getExportRenderRect" in app_js
    assert "mapExportPoint" in app_js
    assert "智能跟拍裁切" in app_js
    assert "getContainedRect" in app_js
    assert "getCanvasVideoRect" in app_js
    assert "drawReframeGuide" in app_js
    assert "previewReframe" in app_js
    assert 'id="downloadEdlBtn"' in html
    assert "downloadEditDecisionList" in app_js
    assert "buildEdl" in app_js
    assert './edit-formats.js' in html
    assert 'id="highlightDuration"' in html
    assert './highlight-selection.js' in html
    assert "selectByDuration" in app_js
    assert 'id="capabilityDisclosure"' in html
    assert "renderCapabilityDisclosure" in app_js
    assert "analysisCapabilities" in app_js
    assert ".capability-disclosure" in styles
    assert 'id="reviewProgress"' in html
    assert 'id="nextUnreviewedBtn"' in html
    assert 'id="confirmNextBtn"' in html
    assert "getReviewStats" in app_js
    assert "navigateNextUnreviewed" in app_js
    assert "confirmCurrentAndContinue" in app_js
    assert 'id="downloadContactSheetBtn"' in html
    assert "downloadContactSheet" in app_js
    assert "waitForLoadedMetadata" in app_js
    assert "正在提取击球关键帧" in app_js
    assert 'id="reviewPlaybackRate"' in html
    assert 'id="loopReview"' in html
    assert "setReviewLoop" in app_js
    assert "updateReviewLoop" in app_js
    assert "preferenceStorageKey" in app_js
    assert "saveEditorPreferences" in app_js
    assert "loadEditorPreferences" in app_js
    assert 'id="exportPlanSummary"' in html
    assert 'id="exportPlanList"' in html
    assert "renderExportPlan" in app_js
    assert ".export-plan-row" in styles
    assert "excludedExportKeys" in app_js
    assert "exportSegmentKey" in app_js
    assert "getRawExportSegments" in app_js
    assert 'id="dataInsights"' in html
    assert "buildDataInsights" in app_js
    assert "renderDataInsights" in app_js
    assert ".data-insight" in styles
    assert "formatEtaWithClock" in app_js
    assert "约 ${clock} 完成" in app_js
    assert 'id="showActivityRegion"' in html
    assert "activityRegion" in app_js
    assert "活动区域代理" in app_js
    assert 'id="timelineZoom"' in html
    assert 'id="timelineRangeLabel"' in html
    assert "getTimelineViewport" in app_js
    assert "centerTimelineOn" in app_js
    assert "source_fingerprint" in app_js
    assert "project_version" in app_js
    assert "项目指纹时长与当前视频不匹配" in app_js
    assert "validActivityRegion" in app_js
    assert 'id="cameraAngle"' in html
    assert "cameraAngle" in app_js
    assert "normalizedVideoPoint(event)" in app_js
    assert 'id="retryEnvironmentBtn"' in html
    assert "environmentReady" in app_js
    assert "serviceVersion" in app_js
    assert "每分钟有效击球" in app_js
    assert "项目数据量超过本地编辑器安全限制" in app_js
    assert 'id="creatorName"' in html
    assert 'id="previewWatermark"' in html
    assert "getBrandLabel" in app_js
    assert "updateBrandUi" in app_js
    assert 'id="previousFrameBtn"' in html
    assert 'id="nextFrameBtn"' in html
    assert "stepVideoFrame" in app_js
    assert "direction / frameRate" in app_js
    assert 'id="evidenceDistribution"' in html
    assert "renderEvidenceDistribution" in app_js
    assert "function median" in app_js
    assert ".evidence-meter" in styles
    assert 'id="projectSaveStatus"' in html
    assert "setProjectSaveStatus" in app_js
    assert "正在保存本机项目" in app_js
    assert 'id="videoPreflight"' in html
    assert "renderVideoPreflight" in app_js
    assert "formatFileSize" in app_js
    assert "deleteTrainingHistory" in app_js
    assert 'aria-label="删除训练记录"' in app_js
    assert 'id="exportReadinessSummary"' in html
    assert "./export-readiness.js" in html
    assert "./review-metrics.js" in html
    assert "buildExportReadiness" in app_js
    assert "renderExportReadiness" in app_js
    assert "#exportReadinessList" in styles
    assert "buildCandidateReviewMetrics" in app_js
    assert "候选命中率" in app_js
    assert 'state.analysisQuality ? String(activeEvents.length) : "--"' in app_js
    assert 'state.analysisQuality ? String(selectedHighlights.length) : "--"' in app_js
    print("Frontend timeline playhead contract passed.")


if __name__ == "__main__":
    run()
